PORT: 8082

# For CICD
VERSION: v0.5.0 # must follow pattern vXX.XX.XX for auto tag in CI

DB_HOST: localhost
DB_PORT: 3306
DB_NAME: ecommerce_db
DB_USER: admin
DB_PASSWORD: admin

CLOUDINARY_NAME: damzcas3k
CLOUDINARY_API_KEY: 332611833886276
CLOUDINARY_API_SECRET: CApeUOYt-JIgUSj9LvSAs6rO610
CLOUDINARY_SECURE: true


# 24h
ACCESS_TOKEN_EXPIRE_IN_MINUTE: 1440
# 7 days
REFRESH_TOKEN_EXPIRE_IN_DAYS: 7
TOKEN_SECRET: "SuPerSecreTBeliEvEmE"

